language: python
sudo: false
cache:
- pip
python:
- '3.5'
- '3.6'
- 'nightly'
matrix:
  fast_finish: true
  allow_failures:
  - python: 'nightly'
install:
- pip install -r requirements-dev.txt
- pip install -U codecov
script:
- coverage run --source yeelib -m pytest tests
after_success:
- codecov
deploy:
  provider: pypi
  user: codingjoe
  password:
    secure: jn763GkmO/nM7TJ9sekgBbFRMI1Z8XijY4ej1ztcJgIwWvZlAWga02sBEnjyFzeqnNmYWAnM50F0oLAvPxmhwIFEUGby2h2Ppy3RhyyNsYi3nQiFKC9/rr0oMJG3xtqyGIJx35pyMM8IzrwQ/tDAcdBRl4HgxnDTLAjgf6Wb1mOhwvQ+/+AZqVqHS0IdXM80K/SgO6LsgL1HgBHdJ7m9i/FUmP5RfDXAPIddd5n81Y73y0ylqsHFgSh8/LtAEcmlJEQIkZDp3jJYM5vxzV4h0LQ6vU7Y1p9RnC6cKEQd+d70iAr+p9apwlwRshaYGy8QVdSbt1vPzpx3mg1Jj1+JpaTmjkC6Ki3XGwcLtARc4MeARnrtB8o0R+QP3KnbfxxQ1SFmvfglZo2HXss6PBB2r6XhAqz7n3zwa7FDqkPb01sytXumnIjckD1E+68X4bR31i627wtIJ5DzTfJYbXAcLbwIPcvnwtEqtmP5IVZJW+xl7ImuyTeslDMx9lT56r2SuGeXZ/B1FRuCRa0hkWasY2DRRo+xrlfleAoMCrLTGKewnNtu9R6r8F1nPUIboLBpirqYStgD86La4uFJai8yer92zNnAue1q7gqj6hAEzoBITGxvDMiy1huWnvnVXP2R9AU/G+oFIGQgbBrXwOVDqeTHla9MGfID3j9rWSi1oNs=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: codingjoe/yeelib
