name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:

  dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
      - run: python -m pip install --upgrade pip setuptools wheel twine readme-renderer
      - uses: actions/checkout@v2
      - run: python setup.py sdist bdist_wheel
      - run: python -m twine check dist/*

  pytest:

    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - 3.9
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade Python setuptools
        run: python -m pip install --upgrade pip setuptools wheel codecov
      - name: Run tests
        run: python setup.py test
      - run: codecov
